# Generated by Django 3.2.6 on 2021-09-10 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wedding',
            name='price_rent',
        ),
    ]
