# Generated by Django 3.2.6 on 2021-09-13 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingApp', '0002_remove_wedding_price_rent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishesanddrink',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='wedding',
            name='menu_price',
        ),
        migrations.RemoveField(
            model_name='wedding',
            name='service_price',
        ),
        migrations.AddField(
            model_name='dishesanddrink',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='wedding',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
