# Generated by Django 3.2.6 on 2021-09-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingApp', '0003_auto_20210913_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_images',
            field=models.ImageField(default=None, upload_to='images/%Y/%m'),
        ),
    ]
