# Generated by Django 3.2.6 on 2021-09-14 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingApp', '0004_menu_menu_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='total_money',
        ),
    ]
