# Generated by Django 3.2.6 on 2021-09-15 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingApp', '0006_menu_total_money'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weddinghall',
            name='date_time_rent',
        ),
    ]
