# Generated by Django 3.2.6 on 2021-09-23 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingApp', '0008_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wedding',
            name='wedding_name',
        ),
    ]
