# Generated by Django 3.2.6 on 2021-09-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingApp', '0010_action_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding',
            name='organize_date',
            field=models.DateTimeField(null=True),
        ),
    ]
