# Generated by Django 3.2.6 on 2021-09-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingApp', '0011_wedding_organize_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding',
            name='wedding_images',
            field=models.ImageField(default=None, upload_to='images/%Y/%m'),
        ),
    ]
