# Generated by Django 3.2.6 on 2021-09-24 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingApp', '0012_wedding_wedding_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weddinghall',
            name='capacity',
        ),
    ]
