# Generated by Django 3.2.6 on 2021-09-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingApp', '0014_auto_20210926_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wedding',
            name='organize_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='action',
            unique_together={('wedding', 'creator')},
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('wedding', 'creator')},
        ),
    ]
