# Generated by Django 3.2.6 on 2021-10-01 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingApp', '0015_auto_20210929_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeddingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu', to='WeddingApp.menu')),
                ('service_items', models.ManyToManyField(null=True, to='WeddingApp.Service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
                ('weddinghall_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weddinghall', to='WeddingApp.weddinghall')),
            ],
        ),
    ]
