# Generated by Django 3.2.6 on 2021-10-01 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingApp', '0016_weddingcart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeddingCart',
        ),
    ]
