# Generated by Django 3.2.6 on 2021-10-02 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingApp', '0017_delete_weddingcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishesanddrink',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='wedding_images',
            field=models.ImageField(default='images/2021/09/top-hinh-nen-bong-da-dep-26.jpg', upload_to='images/%Y/%m'),
        ),
    ]
