# Generated by Django 3.2.6 on 2021-10-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingApp', '0018_auto_20211002_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dishesanddrink',
            options={'verbose_name_plural': 'Món ăn'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name_plural': 'Thưc đơn'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name_plural': 'Dịch vụ'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Người dùng'},
        ),
        migrations.AlterModelOptions(
            name='weddinghall',
            options={'verbose_name_plural': 'Sảnh cưới'},
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
