# Generated by Django 3.2.6 on 2021-10-11 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingApp', '0019_auto_20211010_1855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name_plural': 'Thực đơn'},
        ),
    ]
