# Generated by Django 3.2.6 on 2021-10-11 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingApp', '0020_alter_menu_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='total_money',
        ),
    ]
