# Generated by Django 3.2.6 on 2021-10-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingApp', '0021_remove_menu_total_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wedding',
            name='wedding_images',
            field=models.ImageField(default='images/2021/09/dam-cuoi-khao-khat-5.jpg', upload_to='images/%Y/%m'),
        ),
    ]
