# Generated by Django 3.2.6 on 2021-10-16 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingApp', '0022_alter_wedding_wedding_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='time_rent',
        ),
    ]
