# Generated by Django 3.2.6 on 2021-11-01 09:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingApp', '0023_remove_service_time_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 11, 1, 9, 38, 43, 230697, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
